### ISSUE TITLE
Exception if formatter doesn't have a _fmt attribute

### ISSUE THREAD

**Issue by russss** [brandon-rhodes/logging_tree#12]
Some formatters don't have a `_fmt` attribute (for example, the `LogstashFormatterVersion1` from python-logstash). Logging_tree shouldn't assume that all formatters have a format string.

(Excellent tool otherwise, thanks!)

**Comment by brandon-rhodes** [comment]
Someone subclassed `Formatter` but neglected to call its `__init__()`? Figures. That is a perpetual problem in a language that made it as difficult to do the Right Thing and call parent constructors as the Python 2 series did. Not its strong point, I suppose.

Let me take a look at getting a fix out tonight — thanks so much for reporting this!

**Comment by brandon-rhodes** [comment]
There! I have released 1.6 which I think should work for you. Let me know if you have further problems.
