### ISSUE TITLE
document what broken .parent means, and how to fix it

### ISSUE THREAD

**Issue by graingert** [brandon-rhodes/logging_tree#18]
I'm getting this warning but I'm not sure what to do about it:
```
   o !-"basic"
   |   Broken .parent! Messages propagate to "celery.task"
   |   Level NOTSET so inherits level INFO
   |   Handler <kombu.log.NullHandler object at 0x7f67b630a2e8>
```

**Comment by brandon-rhodes** [comment]
That's an interesting idea! Where would you recommend that such documentation go — if it were on the PyPI page for logging tree, do you think users would find it?

**Comment by graingert** [comment]
Probably a section around here?
https://github.com/brandon-rhodes/logging_tree/blob/master/logging_tree/__init__.py#L66

**Comment by brandon-rhodes** [comment]
I started writing something, then realized the fragility of relying on users to go find documentation to understand the tool. So instead I've improved the way it displays None parents! Hopefully this addresses your use case well enough.

**Comment by graingert** [comment]
Still not really sure what a broken parent means or how to fix it
