### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by FedericoCeratto** [brandon-rhodes/logging_tree#22]
Hello and thanks for developing logging-tree. 
Does it support Python 3.8? I'm running into an error in the tests:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948974

**Comment by brandon-rhodes** [comment]
Yes, it supports Python 3.8 — thanks for the question! It looks like Python 3.8 has added a new logger in one situation, so a test had to be adjusted to expect the new logger to appear in the tree. I have fixed the test, updated the classifiers to advertise compatibility with Python all through way through 3.8, and have released a new version of logging tree.

Please let me know if you run into any more problems!
