### ISSUE TITLE
Document symbol for propagate

### ISSUE THREAD

**Issue by roysmith** [brandon-rhodes/logging_tree#31]
Some nodes show up as:

`   o   "pywiki"
`
others show up as

`   o<--"requests"
`

I'm assuming the ones with a left-pointing arrow are where propagate is True, and the ones with no arrow are where propagate is False?  Assuming that's correct, it should be added to the documentation.

**Comment by wimglenn** [comment]
The assumption looks correct:
https://github.com/brandon-rhodes/logging_tree/blob/1.9/logging_tree/format.py#L56-L61

**Comment by brandon-rhodes** [comment]
You just-so-happened to bump this issue up on my dashboard on a morning when I had a bit of time free, and when I'd already been thinking that `logging_tree` needs to catch up and start bragging that it's also compatible with the new Pythons through 3.12. So I just rewrote its docs and released, being sure to explain what the little 'propagate' arrow means.
