### ISSUE TITLE
Add support for printout(node_name: str)

### ISSUE THREAD

**Issue by bestekov** [brandon-rhodes/logging_tree#32]
In an environment with a lot of different loggers configured (especially by 3rd party modules) it would be useful to be able to filter the tree to a particular starting root. The `printout` method has a `node` parameter, but it appears to require passing a node object rather than the name of the node.

Is there a way to either easily get a node object by name? Barring that would ideally like to be able to pass the name of the target logger to the printout method.

**Comment by brandon-rhodes** [comment]
I think that the Standard Library call `logging.getLogger()` will let you pass a name, and return its node. Try it out and see whether it works!

**Comment by brandon-rhodes** [comment]
I'm going to go ahead and close this issue, in the hope that your silence means that `logging.getLogger()` accomplished your goal, and that you are now able to fetch nodes by name. Please feel free to make further comments here, though, even with the issue closed, if you have any final follow-up questions about its use!
